###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "name": "kamal3", 
    "email": "kamal3@gmail.com",
    "password": "pass",
    "age": 18,
    "gender": "ff",
    "genderPreference": "female"
}

###
POST  https://tinder-app-6elr.vercel.app/api/auth/login
Content-Type: application/json

{ 
    "email": "kamal@gmail.com",
    "password": "password"
}

###
POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{ 
    "email": "jessica23@example.com",
    "password": "password123"
}

###
POST  http://localhost:5000/api/auth/logout

###
GET  http://localhost:5000/api/auth/me