###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "name": "kamal", 
    "email": "kamal@gmail.com",
    "password": "password",
    "age": 18,
    "gender": "male",
    "genderPreference": "female"
}

###
GET http://localhost:5000/api/auth/login